### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by 0dikpah** [brandon3055/BrandonsCore#11]
[fml-client-latest.zip](https://github.com/brandon3055/BrandonsCore/files/496261/fml-client-latest.zip)

don't know what the problem is but i think it can be the coremod. please reply if you know what the issue is.

**Comment by GreatOrator** [comment]
Please post your issue using the template provided for faster response.

## Description

## Base information
* Minecraft version:
* Minecraft Forge version:
* Draconic Evolution version:

## Mod List or Mod Pack (include version)
...
list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by 0dikpah** [comment]
nvm^^ had 2 versions of same mod
