### ISSUE TITLE
crashes with an exit code

### ISSUE THREAD

**Issue by ddarkpais1999** [brandon3055/BrandonsCore#116]
crashes with an exit code when installed with Ice and Fire:Dragons.

**Comment by FoxMcloud5655** [comment]
A known issue, but it wasn't logged here on GitHub.  It's actually specifically with FTB, Ice & Fire, and Draconic Evolution.

**Comment by ddarkpais1999** [comment]
so what can be done to fix it?

**Comment by FoxMcloud5655** [comment]
We already took a look at it and couldn't figure out why it's crashing.  You'll have to remove one of the three mods.

**Comment by EtherialMind** [comment]
I reported this on ice&fire's github awhile back and I think I found the issue to be the rendering of Ice &fire's custom main menu background.
