### ISSUE TITLE
Brandon's Core corrupting CodeChickenLib

### ISSUE THREAD

**Issue by Velken** [brandon3055/BrandonsCore#14]
Modpack: FTB Present's Hermit Pack
Modifications: Added Draconic Evolution + Brandon's Core and Immersive Engineering.
Problem: Brandon's Core corrupts CodeChickenLib on launch.
Workaround: deleting CodeChickenLib after closing Mnecraft so it can download a fresh one again.
Confirmation: Removing Brandon's Core the CodeChickenLib doesn't get corrupted (Draconic Evolution display erros saying that the Core is missing, as expected). Also removing Draconic Evolution makes no difference, pointing that is the Core that is corrupting the file.

**Comment by thebigpixl** [comment]
BrandonsCore-1.10.2-2.1.0.48-universal
Draconic-Evolution-1.10.2-2.0.0d.107-universal
CodeChickenLib-1.10.2-2.4.1.97-universal

Can confirm. Runs once, deploader downloads and moves CodeChickenLib to 1.10.2 folder, Client loads completely. Then once you end the session, and load the client again the following report is generated.

[crash-2016-10-15_22.31.18-client.txt](https://github.com/brandon3055/BrandonsCore/files/531595/crash-2016-10-15_22.31.18-client.txt)

 After closing the Launcher/Client and deleting the CodeChickenLib from the mods/1.10.2 folder, the client will launch normally again after going through the normal deploader routine.

**Comment by Unrepentant-Atheist** [comment]
Doesn't corrupt it for me, but version 51 crashes and can't run:

https://gist.github.com/anonymous/7b24e08d57287c6b02266fe135ff807c

**Comment by covers1624** [comment]
Your issue is un related (You need bauables), latest build of Brandons Core fixes the actual issue at hand.
