### ISSUE TITLE
CodeChicken dependency loader is now depreciated.

### ISSUE THREAD

**Issue by tenten8401** [brandon3055/BrandonsCore#15]
Just thought I'd let you know of an issue I've been having lately. Decided to a mod update for CodeChickenCore on one of my packs and ran into this dialog...
![u wot m8](https://i.imgur.com/ZcIrbOQ.png)
Please stop using the CodeChicken deploader.

**Comment by covers1624** [comment]
I am actually the one who wrote the modifications to the dependency downloader. Dont worry, brandons core uses it still so people see the message.

**Comment by tenten8401** [comment]
Ah, sorry about that.

**Comment by C0rn3j** [comment]
Is it Brandon's Core's fault that a folder "1.10.2" keeps getting recreated? The new ChickenLib just stays in the ./mods/ folder instead of ./mods/1.10.2

**Comment by covers1624** [comment]
It is CCC  and brandons core's fault. i pack the dependency downloader inside brandons core. but i derped and didnt remove the dependencies.info file that says what mods to download so it still thinks it needs ccl. ill probably get brandon to push a build soon.

**Comment by C0rn3j** [comment]
Brandon's core had an update, and now it doesn't scream on launch but the /1.10.2/ folder is still being created, what gives?

**Comment by covers1624** [comment]
The folder is there because the DepLoader still works for other mods just not BrandonsCore.

**Comment by C0rn3j** [comment]
Would it be possible to not create the folder if there's no mod to go into it?

**Comment by covers1624** [comment]
Not really, whats the issue with the folder?

**Comment by C0rn3j** [comment]
No actual issue, it's just annoying me to have a needless empty folder.
