### ISSUE TITLE
1.10.2-2.1.0.51 crash

### ISSUE THREAD

**Issue by Heisenbean** [brandon3055/BrandonsCore#16]
Crash log:  
The CodeChicken Dependency Downloader is being phased out and has detected mods using it. The downloader will function as normal but this message serves as a log of what mods are using it. If you are a mod dev, Please phase out all use of the dependency downloader. If you are a normal user, you can follow the instructions at the bottom of the window if you would like. The following mods are being requested to download...   

` "BrandonsCore-1.10.2-2.1.0.51-universal.jar" Wants: CodeChickenLib-2.4.1`    

Don't be alarmed by this window, it is simply so i can log what mods are using the Dependency Downloader. If you would like to report this please follow instructions listed here. Click the OK button to continue.

I cant find where to download `CodeChickenLib-2.4.1`

**Comment by covers1624** [comment]
Download the latest code chicken lib from curse.

**Comment by Heisenbean** [comment]
@covers1624 Thanks a lot!
:)
