### ISSUE TITLE
CodeChickenLib doesn't download or install

### ISSUE THREAD

**Issue by chaNcharge** [brandon3055/BrandonsCore#17]
When I try to start up minecraft with my mods, it's supposed to automatically install codechickenlib, but when I check the folder it's supposed to be in, it's not there and my Minecraft comes up with a message saying it's missing. Here's the fml-client-latest.log file: https://drive.google.com/file/d/0B3ZoX-8LP704ZVI0T2FhY0tUOWM/view?usp=sharing

**Comment by covers1624** [comment]
Code chicken lib will NOT be automatically installed. Grab it from curse.

**Comment by covers1624** [comment]
In addition to this, ccl dmgoes in the mods folder now not /mods/mcver

**Comment by chaNcharge** [comment]
Ok, thank you for your help, however if that is the case, you should change the CurseForge page to say so
