### ISSUE TITLE
Rounding on com.brandon3055.brandonscore.common.utills.Utills.formatNumber(Long)

### ISSUE THREAD

**Issue by huwcbjones** [brandon3055/BrandonsCore#2]
Rounds to integer values when value > 1 billion.
Should give 4 significant figures as the rest of the rounding does.

**Comment by huwcbjones** [comment]
See [gist](https://gist.github.com/huwcbjones/1947ca367458c89a2985) for test that shows the fix.

**Comment by brandon3055** [comment]
This is already fixed and will be in the next release.
