### ISSUE TITLE
Minecraft Crushes 1.10

### ISSUE THREAD

**Issue by Happynger** [brandon3055/BrandonsCore#20]
Minecraft 1.10.2
DE : 1.10.2-2.0.4.142-universal

Log file: http://pastebin.com/t7eJS36T

I just updated the DE and CCC, CCL, etc and got this error.

**Comment by covers1624** [comment]
This isn't Brandon's Core, DE. CCC or CCL. This is some unrelated obscure crash, if you are still getting this i recommend you take this to the forge forums as we have no idea what is going on there.
