### ISSUE TITLE
Conflict with EnderIO RF API?

### ISSUE THREAD

**Issue by enricotagliavini** [brandon3055/BrandonsCore#21]
[crash-2016-12-31_15.19.39-server.txt](https://github.com/brandon3055/BrandonsCore/files/679680/crash-2016-12-31_15.19.39-server.txt)

Server is home server, 2-3 players. Usually nobody is logged in, if the servers runs for a while upon one player logging in server's watchdog kill the server due to 60 seconds tick, basically he game is stuck. The first login works fine, but logins after few hours / days will get the game stuck. I login where there is Ender IO stuff within rendering distance, including RF EnderIO conduits. Now looking at the crash it says there may be a conflict with BC RF API being older. Can I kindly ask you to confirm or deny if this is the case?

The part worrying me is
```
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.10R1.3.1 from BrandonsCore-1.10.2-2.1.2.76-universal.jar).
                    Ender IO needs at least 1.8.9R1.2.0B1 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
```

And other than this I can't really find much stuff. All the mods should be latest version, with few exception, if I didn't missed any. 

Thank you for your help.

**Comment by enricotagliavini** [comment]
Mhm probably not the source of the problem. I installed the Tesla mod, this for rid of all the complains. Sorry for the noise

**Comment by covers1624** [comment]
This issue has nothing to do with DE, EIO is complaining that the API is outdated means nothing. BrandonsCore's RF api is based on the official ports and have yet to have the version info changed.
