### ISSUE TITLE
RF API not updated

### ISSUE THREAD

**Issue by Arkyo** [brandon3055/BrandonsCore#23]
I've installed EnderIO and BrandsCore both 1.10.2. This error happens:

> An unsupported RF API is installed (1.7.10R1.3.1 from BrandonsCore-1.10.2-2.1.3.82-universal.jar).
> Ender IO needs at least 1.8.9R1.2.0B1 and will NOT work with older versions.

So please update RF API

**Comment by covers1624** [comment]
No, that is not what is happening, BC impl of RF is based on the official ports, i will however get brandon to pull my upstream changes for RF.

**Comment by Arkyo** [comment]
Yeah I fixed that.Thank you!
