### ISSUE TITLE
OF Crash on Startup (2.1.3.82, 1.10.2)

### ISSUE THREAD

**Issue by LovelyFlare** [brandon3055/BrandonsCore#24]
OptiFine D4 worked fine with previous version (2.1.2.76) but it crashes with this version.

Log: http://pastebin.com/dffPxpkQ

**Comment by covers1624** [comment]
You Need to install CCL.

**Comment by LovelyFlare** [comment]
Whoops.  Sorry about that.

**Comment by covers1624** [comment]
All good. :)
