### ISSUE TITLE
No Recipes for Draconic items in update

### ISSUE THREAD

**Issue by OmniKhaos77** [brandon3055/BrandonsCore#27]
I have a server that is running All the Mods Lite, and with the update I had to delete my instance client-side.
After re-installation, and launching the game, there are no recipes for any of the Draconic tools/armors in JEI nor does the infusion crafting core have recipes. It's as if crafting via the ICC has been removed.
Please help, if you can.
Draconic Evolution version 1.10.2-2.0.7.168-universal
Brandon's Core version 1.10.2-2.1.3.82-universal

**Comment by brandon3055** [comment]
This is an issue we are currently looking into but the more we debug it the more confusing things get. 
One thing you can try is rolling back immersive engineering from build 55 (I think thats the latest) to build 54. Assuming you can do that with your server setup. I realize that may not be possible on some servers with a lot of users.
