### ISSUE TITLE
Crashes after adding

### ISSUE THREAD

**Issue by XTCProbstA2** [brandon3055/BrandonsCore#35]
Added Draconic Evolution, said I needed it, Crashes after I installed it. New to the making modpacks thing. I'm also right to the point xD

https://paste.ee/p/VOANq

**Comment by XTCProbstA2** [comment]
Still adding more, so idk if the other mods will crash with this one or if i forgot something that the curse website didn't tell me that was a dependent mod

**Comment by covers1624** [comment]
CodeChickenLib is required for DE to run.

**Comment by XTCProbstA2** [comment]
Thank you!!!
