### ISSUE TITLE
Issue with brandonsCore/dragonic evo

### ISSUE THREAD

**Issue by warplord** [brandon3055/BrandonsCore#38]
http://paste.feed-the-beast.com/view/30bc9a3f

This appears ONLY when I have brandons core and draconic evolution installed. The moment I remove them both - this issue is gone.
So I decided to report it here - maybe it has something to do with your mods.

**Comment by covers1624** [comment]
If you have mfr then its a known issue and entirely a load order dependent issue.

**Comment by warplord** [comment]
Ok, is there anything that can be done to play with both mods and not have this issue?

**Comment by covers1624** [comment]
This is entirely on MFR and is due to some stuff they are doing to override the milk bucket. An issue is open over on the MFR tracker. This is not BrandonsCore nor DE.
