### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Shaspir** [brandon3055/BrandonsCore#40]
Saying that I need a redstoneflux mod but cannot find ANY that work

**Comment by YOYOK9** [comment]
V. 1.12
So going to just add to this instead of making a new report on the same topic. Seems the newest way that the COFH Team has implemented their power systems in their core seems to either break the brandons core mod.  

Picture: 
https://puu.sh/wOQqh/ab35d4ba0f.png

**Comment by covers1624** [comment]
No, jump on curseforge and search for Redstone flux.

**Comment by Shaspir** [comment]
There is no Redstone flux on curseforge that doesn't make launcher crash for me

**Comment by covers1624** [comment]
Redstone flux force crashes the game when someone is being dumb and packing the old rf api. Spend 2 mimiutes and look at the crash.

**Comment by YOYOK9** [comment]
If you have miningLib in your pack remove it. That fixes the problem. And redstone flux is on cursforge?

**Comment by covers1624** [comment]
It sure is.

**Comment by Shaspir** [comment]
Yes there is Redstone flux on curseforge, but like I said it crashes. And
as for "repacking" the file was not touched except to install into forge.
There is a problem with the file


On Jul 21, 2017 8:17 AM, "covers1624" <notifications@github.com> wrote:

It sure is.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/brandon3055/BrandonsCore/issues/40#issuecomment-316998155>,
or mute the thread

**Comment by covers1624** [comment]
.. RedstoneFlux specifically crashes the game when another mod tries to use it's old api, look at the crash, at the top you should see what mod is doing it and report it to them, the crash is intended, and you need to report it to the other mod.
