### ISSUE TITLE
Fusion Crafters arent working

### ISSUE THREAD

**Issue by waftygrowlerr** [brandon3055/BrandonsCore#41]
The Fusion Crafters to make Awakened Draconium will not craft. I've tried every type of power to craft the second tier of Fusion Crafters but still no luck...

**Comment by covers1624** [comment]
Picture of your setup please.

**Comment by covers1624** [comment]
No info, closing. Picture of setup is needed and take it to the DE tracker, Make sure there isnt an issue open already.
