### ISSUE TITLE
Crash with Redstone flux and Thermal mods

### ISSUE THREAD

**Issue by GermanGameMiner** [brandon3055/BrandonsCore#50]
I wanted to make a private mod pack.
but Brandom's Core and Draconic's Evulution Crash with Thermal Foundation, Expansion, Dynamics, and Redstone Flux.

**Comment by GermanGameMiner** [comment]
I have f

**Comment by covers1624** [comment]
Please consult https://vazkii.us/br101/ and open a new issue.
