### ISSUE TITLE
My server returns these warnings and im wondering if they are important

### ISSUE THREAD

**Issue by dabestchicken** [brandon3055/BrandonsCore#52]
[BrandonsCoreWarning.txt](https://github.com/brandon3055/BrandonsCore/files/1959308/BrandonsCoreWarning.txt)

MC:1.10.1
BC:2.1.13.133

**Comment by covers1624** [comment]
Yes, ignore them. Also, 1.10 is unsupported, please update to 1.12.

**Comment by dabestchicken** [comment]
thanks<3
