### ISSUE TITLE
Redstone Flux API not listed as a dependency again on Curse

### ISSUE THREAD

**Issue by falkreon** [brandon3055/BrandonsCore#54]
This is basically just a regression of #42 - if you click through to "Dependencies - all types" from BrandonsCore on CurseForge (e.g. https://minecraft.curseforge.com/projects/brandons-core/relations/dependencies ), only CCL is listed.

**Comment by dooferorg** [comment]
Agreed.. Kind of annoying to have to keep retrying loading to find out the dependencies. Just a list with links would be nice!
