### ISSUE TITLE
[1.12.2] Brandon's Core needs CCL version that does not exist

### ISSUE THREAD

**Issue by Sanofus** [brandon3055/BrandonsCore#55]
I cannot start the game because BC is needing CCL 3.2.0. The only available version is 3.1.9.344.

http://chickenbones.net/Pages/links.html

**Comment by AndreiTS** [comment]
http://chickenbones.net/maven/codechicken/CodeChickenLib/1.12.2-3.2.0.345/CodeChickenLib-1.12.2-3.2.0.345-universal.jar

**Comment by covers1624** [comment]
Just pushed the magic button to release CCL 3.2, waiting on curse approval.
