### ISSUE TITLE
I can't start a server it gives an error named as IllegalArgumentException and ExceptionInInitializerError caused by BrandonsCore

### ISSUE THREAD

**Issue by Friqhers** [brandon3055/BrandonsCore#57]
crash report:
https://gist.github.com/Friqhers/8d0f2921c72ac334a2a3247b13fe986f
latest log:
https://gist.github.com/Friqhers/06201870682e2120b94336ff6a792022

**Comment by brandon3055** [comment]
There are only 2 possible ways that crash could occur. You ether have a corrupt jar or another mod (most likely a coremod) is breaking something. I suggest you try re downloading both Brandons Core and Draconic Evolution. If that does not work try removing all of the coremods listed at the top of the crash report. If that fixes the issue then add them back one by one until it breaks again.

**Comment by Friqhers** [comment]
I tried to redownload brandonscore and draconic evolution and it didn't worked.After removing all the coremods it gives the same errors.

crash report:
https://gist.github.com/Friqhers/26f72a4221f01d3039b9a74c7d6ce9ba
latest log:
https://gist.github.com/Friqhers/706d59a43408d4e5124948a32e456242

**Comment by covers1624** [comment]
That is the exact same crash, but thrown from ExtraUtilities, that means its not DE or BrandonsCore at fault, you have another mod in the pack that is screwing with Enums, This is not an issue with ExtraUtilities, BrandonsCore or DE, redownload all your mods. Failing that you will have to remove them one by one until you find the mod at fault.
