### ISSUE TITLE
Draconic Evolution Information Table

### ISSUE THREAD

**Issue by epeeforteyt** [brandon3055/BrandonsCore#59]
Hi, I just had the client crash trying to open your draconic evo explanation tablet. I pass you my crash error.

Thx 

[crash-2018-08-16_21.39.22-client.txt](https://github.com/brandon3055/BrandonsCore/files/2295029/crash-2018-08-16_21.39.22-client.txt)

**Comment by brandon3055** [comment]
This should be fixed with the release of PI
https://minecraft.curseforge.com/projects/project-intelligence
