### ISSUE TITLE
Mod id and name are "Example Mod"

### ISSUE THREAD

**Issue by CrystalMageX** [brandon3055/BrandonsCore#6]
The [mod id and name](https://github.com/brandon3055/BrandonsCore/blob/df94ea8244823351cca143de6c83fa33c0bb526e/src/main/resources/mcmod.info) for *BrandonsCore* are `examplemod`, and `Example Mod`, respectively. Using that id may cause **id conflictts** with other mods. Using that name **confuses users**. The rest of that `mcmod.info` also seems to be taken directly from an example. Every mod should properly fill out their mod info file.

**Comment by brandon3055** [comment]
I have known about this issue for a while but didn't want to push a new version to fix such a small issue.
