### ISSUE TITLE
Server crash caused by brandonscore pls help (not client) at start up

### ISSUE THREAD

**Issue by kartalas1** [brandon3055/BrandonsCore#66]
https://pastebin.com/1R3zvpaL

**Comment by kartalas1** [comment]
https://pastebin.com/ysCqtt4r tried with just 4 mods and get the same crash what should i do ?
![crash](https://user-images.githubusercontent.com/52705484/61047660-a6f00a00-a3e8-11e9-82aa-c6948d4ffb16.png)

**Comment by brandon3055** [comment]
Try re downloading those mods you may have an corrupt jar. This crash should not be happening.

**Comment by kartalas1** [comment]
ok trying

**Comment by brandon3055** [comment]
Just confirmed i have no issues running a server with the exact same mods an forge version.

**Comment by kartalas1** [comment]
https://pastebin.com/VeFAASzT getting same crash again maybe its caused by my java version which java version do you have ?

**Comment by brandon3055** [comment]
1.8.0-211 same as you
I assume your downloading your jars from curse?

**Comment by kartalas1** [comment]
yes i download jars from curse

**Comment by brandon3055** [comment]
Well then.... I am a little confused... The crash report makes no sense at all because its complaining about an issue that does not exist. 'crystal_ıo' is definitely not an invalid property value.
As far as i can tell everything else on your end matches my test server so it should be working....
Only other thing i can think of would be to delete your configs. Or maybe try reinstalling forge.

**Comment by kartalas1** [comment]
nope it doesn't working tried both of them not working. I can play modpacks with these mods single but i can't play with my friends. Sad.

**Comment by brandon3055** [comment]
how are you launching the server?

**Comment by kartalas1** [comment]
java -Xmx2G -Xms2G -jar forge-1.12.2-14.23.5.2768-universal.jar nogui

**Comment by brandon3055** [comment]
Ok can you launch the original pack without my mods?

**Comment by kartalas1** [comment]
didn't try w8

**Comment by kartalas1** [comment]
yes i can launch

**Comment by kartalas1** [comment]
i am gonna try in another pc with your mods

**Comment by kartalas1** [comment]
got same crash ... i think my computers don't like your mods

**Comment by brandon3055** [comment]
I have an idea... Bit of a long shot but give this a try. https://ss.brandon3055.com/30e7a

**Comment by kartalas1** [comment]
https://pastebin.com/pmExN4x5 not working same crash again i think

**Comment by brandon3055** [comment]
Ok another long shot because this change should have absolutely no effect on anything but the property class in question now uses the same format as AE so if this does not work then nether should half the other mods in existance... https://ss.brandon3055.com/a626b

**Comment by brandon3055** [comment]
wait...  if i'm right that may still break...

**Comment by kartalas1** [comment]
https://pastebin.com/w3F8RF4W same

**Comment by kartalas1** [comment]
Waiting Impatiently

**Comment by brandon3055** [comment]
Does your system use a language other than english?

**Comment by kartalas1** [comment]
yes

**Comment by kartalas1** [comment]
trying with english wait lul

**Comment by brandon3055** [comment]
did that work?

**Comment by kartalas1** [comment]
WHAT IT WORKS IS THAT THE PROBLEM OMG

**Comment by kartalas1** [comment]
I feel like an idiot

**Comment by brandon3055** [comment]
<insert facepalm>... 
`return name().toLowerCase();`
By default converts to lowercase unung the system default language.
This is totally my fault not yours. Sorry...

**Comment by brandon3055** [comment]
Theoretically this should work with your language. https://ss.brandon3055.com/743b7
(assuming i have not made the same mistake somwere else...)

**Comment by kartalas1** [comment]
everyone makes mistakes np thanks for help gb

**Comment by kartalas1** [comment]
wait trying with this

**Comment by kartalas1** [comment]
yes it works gj
