### ISSUE TITLE
Is this a bug or a configuration?

### ISSUE THREAD

**Issue by SoyJetixXD** [brandon3055/BrandonsCore#70]
Hello, I have recently played a survival with mods where I had the Brandon Core installed, to be able to play it with the Draconic Evolution, but I realized something and it was that the Zombies cannot take objects or armor (something they do), try put me in creative to check it better and eliminate all the mods except the Brandon's Core and there I found the bug.                       Normally some zombies could grab players' items and armor, but this is not the case.
Thank you for reading...

**Comment by brandon3055** [comment]
Brandons Core has absolutely no effect on mobs picking up items.
The 'canPickUpLoot' flag is set when a zombie spawns. It is a random chance that depends on game difficulty as well as local difficulty. So by default you won't see any zombies that can pickup items unless you are playing in hard mode. However the longer you you stay in one place the more the 'local difficulty' increases which increases the chance of mobs being able to pick up loot.  
This is entirely vanilla behavior.

**Comment by brandon3055** [comment]
Ok so just to make things easier. if you hit F3 and look for "Local Difficulty" ![](https://ss.brandon3055.com/610f4)
If i am reading the spawn code correctly zombies will never spawn with the 'canPickUpLoot' flag unless that is greater than 2

**Comment by SoyJetixXD** [comment]
Thanks for answering, I did the same, set the difficulty greater than 2, and still the same error, I tried again eliminating all the mods (except the Brandon's Cores), if you like you can also check it, I did everything possible so that the Mobs could pick up the objects, but without any result ...
By eliminating Brandon's Core, Mobs can pick up items (obviously on difficulty greater than 2) ...
Thank you for reading

**Comment by brandon3055** [comment]
I really don't know what to tell you...
https://youtu.be/d9baqi57y_I

**Comment by SoyJetixXD** [comment]
I've checked again, my mistake, I'm very sorry, it must have been some mistake of some of my mods ...
Thanks for reading and helping me :)
