### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by artesisss** [brandon3055/BrandonsCore#76]
my game is crashing 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-Mod-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.69-core.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  Quark Plugin (Quark-Mod-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (FoamFix-Mod-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  CoreMod (Aroma1997Core-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 26.10.2020 10:21
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
	at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Block: class com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal has property: type with invalidly named value: crystal_ıo
	at net.minecraft.block.state.BlockStateContainer.func_185919_a(BlockStateContainer.java:117)
	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:77)
	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:62)
	at com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal.func_180661_e(EnergyCrystal.java:93)
	at net.minecraft.block.Block.<init>(Block.java:234)
	at net.minecraft.block.Block.<init>(Block.java:243)
	at com.brandon3055.brandonscore.blocks.BlockBCore.<init>(BlockBCore.java:55)
	at com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal.<init>(EnergyCrystal.java:58)
	at com.brandon3055.draconicevolution.DEFeatures.<clinit>(DEFeatures.java:133)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3467314816 bytes (3306 MB) / 4255121408 bytes (4058 MB) up to 4255121408 bytes (4058 MB)
	JVM Flags: 2 total; -Xms4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 159 mods loaded, 159 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCH   | mcp                               | 9.42                     | minecraft.jar                                   | None                                     |
	| LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2847-universal.jar         | None                                     |
	| LCH   | forge                             | 14.23.5.2847             | forge-1.12.2-14.23.5.2847-universal.jar         | None                                     |
	| LCH   | foamfixcore                       | 7.7.4                    | minecraft.jar                                   | None                                     |
	| LCH   | opencomputers|core                | 1.7.4.153                | minecraft.jar                                   | None                                     |
	| LCH   | fastbench                         | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                  | None                                     |
	| LCH   | actuallyadditions                 | 1.12.2-r149              | Actually-Additions-Mod-1.12.2.jar               | None                                     |
	| LCH   | appliedenergistics2               | rv6-stable-7             | Applied-Energistics-2-Mod-1.12.2.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | baubles                           | 1.5.2                    | Baubles-Mod-1.12.2.jar                          | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.69            | EnderCore-1.12.2.jar                            | None                                     |
	| LCH   | crafttweaker                      | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                   | None                                     |
	| LCH   | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                                 | None                                     |
	| LCH   | modtweaker                        | 4.0.17                   | modtweaker-4.0.17.jar                           | None                                     |
	| LCH   | jei                               | 4.15.0.297               | jei_1.12.2-4.15.0.297.jar                       | None                                     |
	| LCH   | thaumcraft                        | 6.1.BETA26               | Thaumcraft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                      | 2.1.1                    | Redstone-Flux-API-1.12.2.jar                    | None                                     |
	| LCH   | cofhcore                          | 4.6.3                    | CoFH-Core-1.12.2.jar                            | None                                     |
	| LCE   | brandonscore                      | 2.4.17                   | BrandonsCore-1.12.2-2.4.17.208-universal.jar    | None                                     |
	| LC    | cofhworld                         | 1.4.0                    | CoFH-World-1.12.2.jar                           | None                                     |
	| LC    | thermalfoundation                 | 2.6.3                    | Thermal-Foundation-Mod-1.12.2.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | draconicevolution                 | 2.3.22                   | Draconic-Evolution-Mod-1.12.2.jar               | None                                     |
	| LC    | thermalexpansion                  | 5.5.4                    | Thermal-Expansion-Mod-1.12.2.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                           | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.55            | Mantle-Mod-1.12.2.jar                           | None                                     |
	| LC    | tesla                             | 1.0.63                   | Tesla-API-1.12.2.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | chisel                            | MC1.12.2-1.0.2.45        | Chisel-Mod-1.12.2.jar                           | None                                     |
	| LC    | enderiointegrationtic             | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | quark                             | r1.6-178                 | Quark-Mod-1.12.2.jar                            | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.13.0.183        | Tinkers-Construct-Mod-1.12.2.jar                | None                                     |
	| LC    | p455w0rdslib                      | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar                 | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LC    | ae2wtlib                          | 1.0.34                   | AE2-Wireless-Terminal-Library-1.12.2.jar        | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LC    | akashictome                       | 1.2-12                   | AkashicTome-1.2-12.jar                          | None                                     |
	| LC    | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| LC    | aroma1997core                     | 2.0.0.2.b165             | Aroma1997Core-1.12.2.jar                        | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | aroma1997sdimension               | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | astralsorcery                     | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LC    | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                           | None                                     |
	| LC    | badwithernocookiereloaded         | 1.12.2-3.3.16            | Bad-Wither-No-Cookie-Mod-1.12.2.jar             | None                                     |
	| LC    | bdlib                             | 1.14.3.12                | BdLib-1.12.2.jar                                | None                                     |
	| LC    | betterbuilderswands               | 0.13.2                   | Better-Builders-Wands-Mod-1.12.2.jar            | None                                     |
	| LC    | guideapi                          | 1.12-2.1.8-63            | Guide-API-1.12.2.jar                            | None                                     |
	| LC    | bloodmagic                        | 1.12.2-2.4.1-103         | Blood-Magic-Mod-1.12.2.jar                      | None                                     |
	| LC    | bookshelf                         | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | botania                           | r1.10-362                | Botania+r1.10-362.jar                           | None                                     |
	| LC    | carryon                           | 1.12.3                   | Carry-On-Mod-1.12.2.jar                         | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LC    | chameleon                         | 1.12-4.1.3               | Chameleon-Library-1.12.jar                      | None                                     |
	| LC    | chickenchunks                     | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | classiccombat                     | 1.0.1                    | Classic-Combat-Mod-1.12.2.jar                   | None                                     |
	| LC    | cyclopscore                       | 1.6.2                    | CyclopsCore-1.12.2.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | ic2                               | 2.8.186-ex112            | Industrial-Craft-2-Mod-Experimental-1.12.2.jar  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | commoncapabilities                | 2.4.4                    | CommonCapabilities-1.12.2-2.4.4.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | refinedstorage                    | 1.6.15                   | Refined-Storage-Mod-1.12.2.jar                  | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LC    | compactmachines3                  | 3.0.18                   | Compact-Machines-Mod-1.12.2.jar                 | None                                     |
	| LC    | compactsolars                     | 1.12.2-5.0.18.341        | CompactSolars-Mod-1.12.2.jar                    | None                                     |
	| LC    | computercraft                     | 1.80pr1                  | ComputerCraft-Mod-1.12.2.jar                    | None                                     |
	| LC    | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                   | None                                     |
	| LC    | waila                             | 1.8.26                   | Hwyla-Mod-1.12.2.jar                            | None                                     |
	| LC    | danknull                          | 1.7.101                  | DankNull-Mod-1.12.2.jar                         | 644f38521a349310a5dae0239577dc7beebefaec |
	| LC    | darkutils                         | 1.8.226                  | DarkUtils-1.12.2-1.8.226.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | diethopper                        | 1.1                      | Diet-Hoppers-Mod-1.12.2.jar                     | None                                     |
	| LC    | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387 (3).jar               | None                                     |
	| LC    | eleccore                          | 1.9.452                  | ElecCore-1.12.2.jar                             | None                                     |
	| LC    | enderiobase                       | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | enderioconduits                   | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | opencomputers                     | 1.7.4.153                | OpenComputers-Mod-1.12.2.jar                    | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | enderiointegrationforestry        | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | enderiointegrationticlate         | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | ftblib                            | 5.4.4.4                  | FTBLib-1.12.2.jar                               | None                                     |
	| LC    | enderiomachines                   | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | enderiopowertools                 | 5.1.51                   | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LC    | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | valkyrielib                       | 1.12.2-2.0.20.1          | ValkyrieLib-1.12.2.jar                          | None                                     |
	| LC    | environmentaltech                 | 1.12.2-2.0.20.1          | Environmental-Tech-Mod-1.12.2.jar               | None                                     |
	| LC    | extrautils2                       | 1.0                      | Extra-Utilities-Mod-1.12.2.jar                  | None                                     |
	| LC    | zerocore                          | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                     | None                                     |
	| LC    | bigreactors                       | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar             | None                                     |
	| LC    | quickleafdecay                    | 1.2.4                    | Fast-Leave-Decay-Mod-1.12.2.jar                 | None                                     |
	| LC    | fastfurnace                       | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                    | None                                     |
	| LC    | foamfix                           | 0.10.5-1.12.2            | FoamFix-Mod-1.12.2.jar                          | None                                     |
	| LC    | forgemultipartcbe                 | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | microblockcbe                     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LC    | minecraftmultipartcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LC    | ftbutilities                      | 5.4.0.122                | FTB-Utilities-Mod-1.12.2.jar                    | None                                     |
	| LC    | ftbbackups                        | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.2.jar                 | None                                     |
	| LC    | funkylocomotion                   | 1.0                      | Funky-Locomotion-Mod-1.12.2.jar                 | None                                     |
	| LC    | gendustry                         | 1.6.5.8                  | Gendustry-Mod-1.12.2.jar                        | None                                     |
	| LC    | gravestone                        | 1.0.12                   | Gravestone-Mod-1.12.jar                         | None                                     |
	| LC    | harvestcraft                      | 1.12.2zb                 | HarvestCraft-Mod-1.12.2.jar                     | None                                     |
	| LC    | ichunutil                         | 7.2.2                    | iChun-Util-Mod-1.12.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | railcraft                         | 12.0.0-beta-5            | Railcraft-Mod-1.12.2.jar                        | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | immersiveengineering              | 0.12-98                  | Immersive-Engineering-Mod-1.12.2.jar            | None                                     |
	| LC    | immersivepetroleum                | 1.1.9                    | Immersive-Petroleum-Mod-1.12.2.jar              | None                                     |
	| LC    | forgelin                          | 1.8.4                    | Shadowfacts-Forgelin-1.12.2.jar                 | None                                     |
	| LC    | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing               | 1.12.2-1.12.2            | Industrial-Foregoing-Mod-1.12.2.jar             | None                                     |
	| LC    | integrateddynamics                | 1.1.0                    | IntegratedDynamics-1.12.2-1.1.0.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | integrateddynamicscompat          | 1.0.0                    | IntegratedDynamics-1.12.2-1.1.0.jar             | None                                     |
	| LC    | integratedtunnels                 | 1.6.10                   | IntegratedTunnels-1.12.2-1.6.10.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | integratedtunnelscompat           | 1.0.0                    | IntegratedTunnels-1.12.2-1.6.10.jar             | None                                     |
	| LC    | nuclearcraft                      | 2.15a                    | NuclearCraft-Mod-1.12.2.jar                     | None                                     |
	| LC    | mcjtylib_ng                       | 3.5.4                    | McJtyLib-1.12.2.jar                             | None                                     |
	| LC    | rftools                           | 7.70                     | RFTools-Mod-1.12.2.jar                          | None                                     |
	| LC    | integrationforegoing              | 1.12.2-1.9               | Integration-Foregoing-Mod-1.12.2.jar            | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LC    | inventorysorter                   | 1.13.3+57                | Inventory-Sorter-Mod-1.12.2.jar                 | None                                     |
	| LC    | inventorytweaks                   | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironbackpacks                     | 1.12.2-3.0.8-12          | Iron-Backpacks-Mod-1.12.2.jar                   | None                                     |
	| LC    | ironchest                         | 1.12.2-7.0.67.844        | Iron-Chests-Mod-1.12.2.jar                      | None                                     |
	| LC    | jeibees                           | 0.9.0.5                  | JEI-Bees-Mod-1.12.2.jar                         | None                                     |
	| LC    | journeymap                        | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                     | None                                     |
	| LC    | libvulpes                         | 0.4.0.-57                | LibVulpes-1.12.2.jar                            | None                                     |
	| LC    | magicbees                         | 1.0                      | Magic-Bees-Mod-1.12.2.jar                       | None                                     |
	| LC    | mcmultipart                       | 2.5.3                    | MCMultiPart-Mod-1.12.2.jar                      | None                                     |
	| LC    | mercurius                         | 1.0.6                    | Mercurius-Mod-1.12.2.jar                        | None                                     |
	| LC    | mob_grinding_utils                | 0.3.13                   | MobGrindingUtils-0.3.13.jar                     | None                                     |
	| LC    | numina                            | 1.12.2-1.0.36            | Numina-Mod-1.12.2.jar                           | None                                     |
	| LC    | powersuits                        | 1.12.2-1.0.39            | Modular-Powersuits-Mod-1.12.2.jar               | None                                     |
	| LC    | movingelevators                   | 1.2.4                    | Moving-Elevators-Mod-1.12.2.jar                 | None                                     |
	| LC    | mrtjpcore                         | 2.1.4.43                 | MrTJPCore-1.12.2.jar                            | None                                     |
	| LC    | mystcraft                         | 0.13.7.04                | Mystcraft-Mod-1.12.2.jar                        | None                                     |
	| LC    | netherportalfix                   | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar               | None                                     |
	| LC    | nomobbat                          | 1.1                      | NoBat-1.12.2-frg14.23.3.2655.jar                | None                                     |
	| LC    | placebo                           | 1.6.0                    | Placebo-1.12.2.jar                              | None                                     |
	| LC    | pneumaticcraft                    | 1.12.2-0.11.14-395       | PneumaticCraft-Mod-1.12.2.jar                   | None                                     |
	| LC    | projectred-core                   | 4.9.4.120                | ProjectRed-Base-1.12.2.jar                      | None                                     |
	| LC    | projectred-integration            | 4.9.4.120                | ProjectRed-Integration-1.12.2.jar               | None                                     |
	| LC    | projectred-transmission           | 4.9.4.120                | ProjectRed-Integration-1.12.2.jar               | None                                     |
	| LC    | rangedpumps                       | 0.5                      | Ranged-Pumps-Mod-1.12.2.jar                     | None                                     |
	| LC    | reborncore                        | 3.16.3.476               | RebornCore-1.12.2-3.16.3.476-universal.jar      | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | rebornstorage                     | 1.0.0                    | RebornStorage-1.12.2-3.3.4.1.jar                | None                                     |
	| LC    | redstonearsenal                   | 2.6.6                    | Redstone-Arsenal-Mod-1.12.2.jar                 | None                                     |
	| LC    | refinedstorageaddons              | 0.4.4                    | refinedstorageaddons-0.4.4.jar                  | None                                     |
	| LC    | rftoolscontrol                    | 2.0.2                    | RFTools-Control-Mod-1.12.2.jar                  | None                                     |
	| LC    | rftoolsdim                        | 5.70                     | RFTools-Dimensions-Mod-1.12.2.jar               | None                                     |
	| LC    | simplegenerators                  | 1.12.2-2.0.20.2          | Simple-Generators-Mod-1.12.2.jar                | None                                     |
	| LC    | thermaldynamics                   | 2.5.6                    | Thermal-Dynamics-Mod-1.12.2.jar                 | None                                     |
	| LC    | simplyjetpacks                    | 2.2.11.64                | Simply-Jetpacks-2-Mod-1.12.2.jar                | None                                     |
	| LC    | stevescarts                       | 2.4.31.135               | StevesCarts-1.12.2-2.4.31.135.jar               | None                                     |
	| LC    | storagedrawers                    | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                 | None                                     |
	| LC    | storagedrawersextra               | @VERSION@                | Storage-Drawers-Extras-Mod-1.12.2.jar           | None                                     |
	| LC    | thaumictinkerer                   | 1.12.2-5.0-353c71c       | Thaumic-Tinkerer-Mod-1.12.2.jar                 | None                                     |
	| LC    | thermalcultivation                | 0.3.6                    | Thermal-Cultivation-Mod-1.12.2.jar              | None                                     |
	| LC    | thermalinnovation                 | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thutcore                          | 5.21.0                   | thutcore-1.12.2-5.21.0.jar                      | None                                     |
	| LC    | thutcore_compat                   | 1.0                      | thutcore-1.12.2-5.21.0.jar                      | None                                     |
	| LC    | thuttech                          | 6.0.8                    | Thutmoses-Elevators-Mod-1.12.1.jar              | None                                     |
	| LC    | translocators                     | 2.5.2.81                 | Translocators-1.12.2-2.5.2.81-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | universalmodifiers                | 1.12.2-1.0.16.1          | ValkyrieLib-1.12.2.jar                          | None                                     |
	| LC    | wanionlib                         | 1.12.2-2.4               | WanionLib-1.12.2.jar                            | None                                     |
	| LC    | wct                               | 3.12.97                  | WirelessCraftingTerminal-1.12.2-3.12.97.jar     | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LC    | xnet                              | 1.8.2                    | XNet-Mod-1.12.2.jar                             | None                                     |
	| LC    | eleccoreloader                    | 1.9.452                  | ElecCore-1.12.2.jar                             | None                                     |
	| LC    | mysticallib                       | 1.12.2-1.6.0             | MysticalLib-1.12.2.jar                          | None                                     |
	| LC    | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | None                                     |
	| LC    | unidict                           | 1.12.2-2.9.3             | UniDict-Mod-1.12.2.jar                          | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-Mod-1.12.2.jar)
  li.cil.oc.common.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.69-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
Quark Plugin (Quark-Mod-1.12.2.jar)
  vazkii.quark.base.asm.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (FoamFix-Mod-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12.2.jar)
  
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

pls help me what is it

**Comment by FoxMcloud5655** [comment]
You'll need to provide us with the version of CodeChickenLibrary and Brandon's Core that you're using.

**Comment by artesisss** [comment]
> You'll need to provide us with the version of CodeChickenLibrary and Brandon's Core that you're using.
codechicken:3.2.3.358
brandons:2.4.12.205

**Comment by FoxMcloud5655** [comment]
There's your problem.  Your build of Brandon's Core is 4 versions out of date.  Update to 1.12.2-2.4.19.214, and you won't see this crash again.

**Comment by artesisss** [comment]
> There's your problem. Your build of Brandon's Core is 4 versions out of date. Update to 1.12.2-2.4.19.214, and you won't see this crash again.

thanks

**Comment by FoxMcloud5655** [comment]
If this fixed your issue, please close it!

**Comment by covers1624** [comment]
Closing due to no response.
