### ISSUE TITLE
Crach

### ISSUE THREAD

**Issue by gagaos** [brandon3055/BrandonsCore#77]
my games crash i don't know why.

Mod List:
![Capture d’écran 2021-05-01 175446](https://user-images.githubusercontent.com/83508369/116787788-80f89580-aaa6-11eb-9dfa-a01025870990.png)

the game logs:
https://paste.ee/p/0qU01

**Comment by gagaos** [comment]
other log
https://paste.ee/p/WONrw

the old log
[crash-2021-05-01_17.27.39-client.txt](https://github.com/brandon3055/BrandonsCore/files/6409868/crash-2021-05-01_17.27.39-client.txt)
[crash-2021-05-01_17.30.08-client.txt](https://github.com/brandon3055/BrandonsCore/files/6409869/crash-2021-05-01_17.30.08-client.txt)
[crash-2021-05-01_17.38.18-server.txt](https://github.com/brandon3055/BrandonsCore/files/6409870/crash-2021-05-01_17.38.18-server.txt)
[crash-2021-05-01_17.39.25-server.txt](https://github.com/brandon3055/BrandonsCore/files/6409871/crash-2021-05-01_17.39.25-server.txt)
[crash-2021-05-01_17.41.42-server.txt](https://github.com/brandon3055/BrandonsCore/files/6409872/crash-2021-05-01_17.41.42-server.txt)
[crash-2021-05-01_17.42.33-server.txt](https://github.com/brandon3055/BrandonsCore/files/6409873/crash-2021-05-01_17.42.33-server.txt)
[crash-2021-05-01_17.48.11-server.txt](https://github.com/brandon3055/BrandonsCore/files/6409874/crash-2021-05-01_17.48.11-server.txt)
[crash-2021-05-01_17.58.48-server.txt](https://github.com/brandon3055/BrandonsCore/files/6409875/crash-2021-05-01_17.58.48-server.txt)
[crash-2021-03-18_17.22.41-client.txt](https://github.com/brandon3055/BrandonsCore/files/6409876/crash-2021-03-18_17.22.41-client.txt)
[crash-2021-03-18_17.24.09-client.txt](https://github.com/brandon3055/BrandonsCore/files/6409877/crash-2021-03-18_17.24.09-client.txt)
[crash-2021-05-01_17.24.57-client.txt](https://github.com/brandon3055/BrandonsCore/files/6409878/crash-2021-05-01_17.24.57-client.txt)
[crash-2021-05-01_17.25.42-client.txt](https://github.com/brandon3055/BrandonsCore/files/6409879/crash-2021-05-01_17.25.42-client.txt)
[crash-2021-05-01_17.26.52-client.txt](https://github.com/brandon3055/BrandonsCore/files/6409880/crash-2021-05-01_17.26.52-client.txt)

**Comment by FoxMcloud5655** [comment]
Your errors are all over the place.  None of them have to do with Brandon's Core.

Your first log says it's Pixelmon (which isn't even in the list), so that's the wrong error report.  Judging from your other logs, however, it appears as if you have two Immersive Engineering coremods running at the same time that are different versions.  Check inside the 1.12.2 folder and delete the oldest IE mod you see if there's two of them.

**Comment by gagaos** [comment]
Thank you I needed a developer and there was "Brandon's Core" in my mod list so but really thank you thank you
