### ISSUE TITLE
Teleporter method

### ISSUE THREAD

**Issue by MrRiegel** [brandon3055/BrandonsCore#8]
Hi, I used your [method](https://github.com/brandon3055/BrandonsCore/blob/1.9/src/main/java/com/brandon3055/brandonscore/utils/Teleporter.java#L171) to teleport the player to another dimension and it seems that the player won't be added to World.loadedEntityList. That's a problem. I tried to add the player manually and edited parts of the method but I couldn't fix it.
Teleporting in minecraft is very hard to understand.

**Comment by brandon3055** [comment]
Yes it is... If your using 1.10 that code was a quick port from the 1.7 version. And i have not done a lot of testing with it yet.
