### ISSUE TITLE
Crash the game from brandoncore

### ISSUE THREAD

**Issue by HellPug1** [brandon3055/BrandonsCore#82]
version game 1.12.2 
![Screenshot_3](https://user-images.githubusercontent.com/89072804/129700101-726fdf8d-a02a-4b3e-a980-baff4383b2b6.png)
![Screenshot_4](https://user-images.githubusercontent.com/89072804/129700231-db48ff91-2ebe-403a-becf-d6661cca3f95.png)
pls help me

**Comment by FoxMcloud5655** [comment]
There is no crash report attached to this.  Therefore, this issue will probably be closed immediately.

**Comment by FoxMcloud5655** [comment]
With that being said, however, your version of Draconic Evolution is horribly out of date.  Update that, and your problem will likely go away.

I would highly recommend checking all your other mods too and making sure they are up to date.

**Comment by covers1624** [comment]
Please open a new issue with a properly attached crash report.
