### ISSUE TITLE
Mekanism 

### ISSUE THREAD

**Issue by CuzImZyaDx** [brandon3055/BrandonsCore#86]
Hi I would like to know, if there would be any existing extensions for 1.12.2 of the mekasuit, I don't want to play in 1.16.5 because the version is heavier, and not having mods that I use in 1.12.2, so if anyone knows if exists, or when it does, I would love to add it to my modpack

**Comment by FoxMcloud5655** [comment]
First of all, I don't know what you mean by "existing extensions"...  Second of all, this is for Brandon's Core which supports Draconic Evolution, not Mekanism.
