### ISSUE TITLE
probleme in the process of loading mods custom modpacks

### ISSUE THREAD

**Issue by TheDarkRainb0w** [brandon3055/BrandonsCore#87]
When starting the compilation a problem on then comes on the brandonscore mode which causes the game to crash and puts me the following error messages:

Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Code de sortie : -1

i try different version of Brandon's Core but all didn't work

**Comment by covers1624** [comment]
This does not give us any useful information.

Please provide your Minecraft crash report.

**Comment by TheDarkRainb0w** [comment]
[crash-2021-12-10_15.03.17-client.txt](https://github.com/brandon3055/BrandonsCore/files/7690150/crash-2021-12-10_15.03.17-client.txt)

**Comment by TheDarkRainb0w** [comment]
here sorry i forgot it

**Comment by covers1624** [comment]
Please update Draconic Additions.

**Comment by TheDarkRainb0w** [comment]
i have the same problem
[crash-2021-12-10_16.08.18-client.txt](https://github.com/brandon3055/BrandonsCore/files/7690234/crash-2021-12-10_16.08.18-client.txt)
e

**Comment by TheDarkRainb0w** [comment]
@covers1624 sorry but the issues is not solved so can you re-open it please

**Comment by TheDarkRainb0w** [comment]
pfff people just don't resolve a problems nicely....

**Comment by covers1624** [comment]
Well, your problem now is you don't have Draconic Evolution installed.. Which is required for DraconicAdditions.
