### ISSUE TITLE
probleme in the process of loading mods custom modpacks 

### ISSUE THREAD

**Issue by TheDarkRainb0w** [brandon3055/BrandonsCore#88]
the problem is not solved so ii have update Draconic Additions but the error steal here so please can you help me

[crash-2021-12-10_16.08.18-client.txt](https://github.com/brandon3055/BrandonsCore/files/7691791/crash-2021-12-10_16.08.18-client.txt)

**Comment by covers1624** [comment]
Please dont open duplicate issues about this.
