### ISSUE TITLE
Minecraft will not launch now that this mod is installed

### ISSUE THREAD

**Issue by JacobMuken** [brandon3055/BrandonsCore#9]
After a few issues and getting this, draconic evolution, CCL, and CCC, and this is my crash report
http://pastebin.com/vsBvNjLe

**Comment by JacobMuken** [comment]
You know what, it's Draconic Evolution, i took it out and it works now. halp

**Comment by covers1624** [comment]
You have installed the deobf version of DE, you need to install the universal version.
the deobf version is for people in development environments.

**Comment by JacobMuken** [comment]
that fixed it, thanks, didn't realize i had the wrong version
