### ISSUE TITLE
My game keeps crashing                                                                                                                                                                         

### ISSUE THREAD

**Issue by Espernos** [brandon3055/BrandonsCore#91]
when i put brandon core in my mods folder my game crashes

this is the error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)

and this is the crash report:  ---- Minecraft Crash Report ----

WARNING: coremods are present:
  wings (wings-1.1.6-1.12.2.jar)
  McLib core mod (mclib-2.0.1-1.12.2.jar)
  HCASM (HammerLib-1.12.2-2.0.6.19.jar)
  LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  pymtech (PymTech-1.12.2-1.0.2.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.20.jar)
  FMLModule (mdxlib-3.0.0.26.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2/23/22 6:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.client.creativetab.DETab.<init>(ILjava/lang/String;Ljava/lang/String;I)V
	at net.foxmcloud.draconicadditions.client.creativetab.DATab.<init>(DATab.java:19)
	at net.foxmcloud.draconicadditions.DAFeatures.<clinit>(DAFeatures.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
	at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1358894920 bytes (1295 MB) / 1959788544 bytes (1869 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 117 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                            | Version            | Source                                             | Signature                                |
	|:----- |:----------------------------- |:------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                     | 1.12.2             | minecraft.jar                                      | None                                     |
	| LCH   | mcp                           | 9.42               | minecraft.jar                                      | None                                     |
	| LCH   | FML                           | 8.0.99.99          | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                         | 14.23.5.2854       | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | lesslag                       | 1.0                | minecraft.jar                                      | None                                     |
	| LCH   | obfuscate                     | 0.4.2              | minecraft.jar                                      | None                                     |
	| LCH   | srm-hooks                     | 1.12.2-1.0.0       | minecraft.jar                                      | None                                     |
	| LCH   | securitycraft                 | v1.8.19.1          | [1.12.2] SecurityCraft v1.8.19.1.jar               | None                                     |
	| LCH   | mdxlib                        | 3.0.0.26           | mdxlib-3.0.0.26.jar                                | None                                     |
	| LCH   | redstoneflux                  | 2.0.1              | RedstoneFlux-1.12-2.0.1.2-universal.jar            | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| LCH   | avp                           | 6.0.0.62           | aliensvspredator-6.0.0.62.jar                      | None                                     |
	| LCH   | artemislib                    | 1.0.6              | ArtemisLib-1.12.2-v1.0.6.jar                       | None                                     |
	| LCH   | codechickenlib                | 3.2.1.350          | CodeChickenLib-1.12.2-3.2.1.350-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | avaritia                      | 3.3.0              | Avaritia-1.12.2-3.3.0.33-universal.jar             | None                                     |
	| LCH   | gorecore                      | 1.12.2-0.4.5       | avatarmod-1.5.17-alpha.jar                         | None                                     |
	| LCH   | avatarmod                     | 1.5.17-alpha       | avatarmod-1.5.17-alpha.jar                         | None                                     |
	| LCH   | baubles                       | 1.5.2              | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | bedrockminer                  | 1.0.5              | BedrockMiner-1.12.2-(v.1.0.5).jar                  | None                                     |
	| LCH   | berzikheroes                  | 2.3                | berzikheroes-2.4.jar                               | None                                     |
	| LCH   | llibrary                      | 1.7.19             | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | mowziesmobs                   | 1.5.6              | mowziesmobs-1.5.6.jar                              | None                                     |
	| LCH   | patchouli                     | 1.0-21             | Patchouli-1.0-21.jar                               | None                                     |
	| LCH   | bewitchment                   | 0.22.20            | bewitchment-1.12.2-0.0.22.20.jar                   | None                                     |
	| LCH   | blockarmor                    | 2.4.11             | BlockArmor-1.12.2-2.4.11.jar                       | None                                     |
	| LCH   | blocklings                    | 1.0                | Blocklings 6.0.1_b - 1.12.2.jar                    | None                                     |
	| LCH   | bookworm                      | 1.12.2-2.5.2.1     | bookworm-1.12.2-2.5.2.1.jar                        | None                                     |
	| LCE   | brandonscore                  | 2.4.19             | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
	| LC    | chiselsandbits                | 14.33              | chiselsandbits-14.33.jar                           | None                                     |
	| LC    | extendedrenderer              | v1.0               | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LC    | coroutil                      | 1.12.1-1.2.37      | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LC    | configmod                     | v1.0               | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LC    | craftstudioapi                | 1.0.0              | CraftStudio-1.0.0.93-mc1.12-alpha.jar              | None                                     |
	| LC    | crafttweaker                  | 4.1.20             | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
	| LC    | ctgui                         | 1.0.0              | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
	| LC    | jei                           | 4.15.0.296         | jei_1.12.2-4.15.0.296.jar                          | None                                     |
	| LC    | crafttweakerjei               | 2.0.3              | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
	| LC    | ctm                           | MC1.12.2-1.0.2.31  | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LC    | custom_superhero_mod          | 0.0.2              | Custom SuperHero ModV0.2.1.jar                     | None                                     |
	| LC    | custombackgrounds             | 1.0                | CustomBackgrounds-MC1.12-1.1.1.jar                 | None                                     |
	| LC    | custommainmenu                | 2.0.9.1            | CustomMainMenu-MC1.12.2-2.0.9.1.jar                | None                                     |
	| LC    | dfheroesexpansion             | 1.3                | DFHeroesExpansion 1.3(non restricted forge).jar    | None                                     |
	| LC    | thedalekmod                   | (Update 58.0.0)    | dm-58.jar                                          | None                                     |
	| LC    | doggytalents                  | 1.15.1.5           | DoggyTalents-1.12.2-1.15.1.5.jar                   | None                                     |
	| LC    | draconicevolution             | 2.3.28             | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| LC    | draconicadditions             | 1.12.1             | Draconic-Additions-1.12.2-1.12.1.34-universal.jar  | None                                     |
	| LC    | durability101                 | 0.0.3              | Durability101-1.12-0.0.3.jar                       | None                                     |
	| LC    | ebwizardry                    | 4.2.11             | ElectroblobsWizardry-4.2.11-MC1.12.2.jar           | None                                     |
	| LC    | ageofabyssalcraft             | 0.7                | Engender Mod-1.12.2-0.7-pre1.jar                   | None                                     |
	| LC    | ageofchaos                    | 0.7                | Engender Mod-1.12.2-0.7-pre1.jar                   | None                                     |
	| LC    | ageofminecraft                | 0.7                | Engender Mod-1.12.2-0.7-pre1.jar                   | None                                     |
	| LC    | epicsiegemod                  | 13.167             | EpicSiegeMod-13.167.jar                            | None                                     |
	| LC    | motnt                         | 1.0.1              | EvenMoreTNT-1.0.1.jar                              | None                                     |
	| LC    | excp                          | 1.0.6              | extraCreepers-1.0.6.jar                            | None                                     |
	| LC    | fastleafdecay                 | v14                | FastLeafDecay-v14.jar                              | None                                     |
	| LC    | fnaf                          | 1.12.2-Dev17       | FNaFUniverseMod~1.12.2-Release 2.5.jar             | None                                     |
	| LC    | fpsreducer                    | mc1.12.2-1.17      | FpsReducer-mc1.12.2-1.17.jar                       | None                                     |
	| LC    | gargoyles                     | 1                  | Gargoyles mod 1.12.2 patch 1.jar                   | None                                     |
	| LC    | generaldisasters              | 1.0                | generaldisasters-1.0.jar                           | None                                     |
	| LC    | gulliverreborn                | 1.10               | Gulliver Reborn mc1.12.2 v1.10.jar                 | None                                     |
	| LC    | hammercore                    | 2.0.6.19           | HammerLib-1.12.2-2.0.6.19.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LC    | shm                           | 0.2                | HeroCore 0.3.jar                                   | None                                     |
	| LC    | heroesarrival                 | 1.0.0              | Heroes Arrival 1.2.1.jar                           | None                                     |
	| LC    | thesuperheroesuniverse        | 1.0                | HeroesUniverse1.0.5 - 1.12.2.jar                   | None                                     |
	| LC    | heroicarmory                  | 1.1.3              | heroicarmory-1.2.0.jar                             | None                                     |
	| LC    | howlingmoon                   | 0.9                | howlingmoon-1.12.2-0.9.jar                         | None                                     |
	| LC    | icbmclassic                   | 1.12.2-3.3.0.63    | ICBM-classic-1.12.2-3.3.0b63.jar                   | None                                     |
	| LC    | iceandfire                    | 1.9.1              | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
	| LC    | ichunutil                     | 7.2.2              | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | improvableskills              | 65r                | ImprovableSkills-1.12.2-65r.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | ironman                       | Beta-1.12.2-1.2.6  | IronMan-1.12.2-Beta-1.12.2-1.2.6.jar               | None                                     |
	| LC    | speedsterheroes               | 1.12.2-2.2.1       | SpeedsterHeroes-1.12.2-2.2.1.jar                   | None                                     |
	| LC    | lucraftcore                   | 1.12.2-2.4.16      | LucraftCore-1.12.2-2.4.16.jar                      | None                                     |
	| LC    | spylcu                        | Beta-1.12.2-2.0.3  | LanternCorpsUniverse-Beta-1.12.2-2.0.3.jar         | None                                     |
	| LC    | raycore                       | 3.2.1.0            | raycore-1.12.2-3.2.1.0.jar                         | None                                     |
	| LC    | mario2                        | 3.2.0.2            | mario2-1.12.2-3.2.0.2.jar                          | None                                     |
	| LC    | mclib                         | 2.0.1              | mclib-2.0.1-1.12.2.jar                             | None                                     |
	| LC    | metamorph                     | 1.2.1              | metamorph-1.2.1-1.12.2.jar                         | None                                     |
	| LC    | mobarmormod                   | 1.0.3b             | Mob Armor Mod V1.0.3b-1.12.2.jar                   | None                                     |
	| LC    | mo_swords                     | v5                 | moSwords-1.12.2v5.jar                              | None                                     |
	| LC    | mtlib                         | 3.0.6              | MTLib-3.0.6.jar                                    | None                                     |
	| LC    | mutantbeasts                  | 1.12.2-0.7.2       | MutantBeasts-1.12.2-0.7.2.jar                      | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
	| LC    | my_hero_academia              | 1.0.0              | My Hero Alpha 0.1.3.1 (Bugfix).jar                 | None                                     |
	| LC    | mam                           | 1.0                | MystAdditions-1.0.jar                              | None                                     |
	| LC    | mysticalworld                 | 1.12.2-1.8.4       | mysticalworld-1.12.2-1.8.4.jar                     | None                                     |
	| LC    | neid                          | 1.5.4.4            | NotEnoughIDs-1.5.4.4.jar                           | None                                     |
	| LC    | subcommonlib                  | 1.2.0.1            | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| LC    | petbuddy                      | $version           | petbuddy-petbuddy-1.12.2-2.4.1.0.jar               | None                                     |
	| LC    | portalgun                     | 7.1.0              | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | prefab                        | 1.3.0.26           | prefab-1.3.0.26.jar                                | None                                     |
	| LC    | projectintelligence           | 1.0.9              | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
	| LC    | pymtech                       | 1.12.2-1.0.2       | PymTech-1.12.2-1.0.2.jar                           | None                                     |
	| LC    | resize                        | 2.2                | resizingpotion-2.2.jar                             | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LC    | scp                           | 2.3.1              | SCP Lockdown-1.12.2-2.3.1-dev.jar                  | None                                     |
	| LC    | secretroomsmod                | 5.6.4              | secretroomsmod-1.12.2-5.6.4.jar                    | None                                     |
	| LC    | shatter                       | 7.0.0              | Shatter-1.12.2-7.0.1.jar                           | None                                     |
	| LC    | specialmobs                   | 1.0.2_for_mc1.12.2 | specialmobs-1.0.2_for_mc1.12.2.jar                 | None                                     |
	| LC    | star-tech                     | 1.1.1              | star-tech-1.1.1.jar                                | None                                     |
	| LC    | sx                            | 0.1.3              | Superheroes X-1.12.2-0.1.3-universal.jar           | None                                     |
	| LC    | tektopia                      | 1.1.0              | tektopia-1.1.0.jar                                 | None                                     |
	| LC    | the-fifth-world               | 0.5                | the-fifth-world-0.5.1.jar                          | None                                     |
	| LC    | the_rising_of_the_shield_hero | 2.1.0              | The_rising_of_the_shield_hero_1.12.2_2.1.0.jar     | None                                     |
	| LC    | tinymobfarm                   | 1.0.5              | TinyMobFarm-1.12.2-1.0.5.jar                       | None                                     |
	| LC    | tlsywen                       | 1.0                | tlsywen-1.1.jar                                    | None                                     |
	| LC    | sm                            | 1.3                | TypicalHeroes-1.0.2.jar                            | None                                     |
	| LC    | ultimate_unicorn_mod          | 1.5.16             | ultimate_unicorn_mod-1.12.2-1.5.16.jar             | None                                     |
	| LC    | vampirism                     | 1.6.2              | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
	| LC    | teamlapen-lib                 | 1.6.2              | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
	| LC    | vehicle                       | 0.44.1             | vehicle-mod-0.44.1-1.12.2.jar                      | None                                     |
	| LC    | wawla                         | 2.6.275            | Wawla-1.12.2-2.6.275.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | wings                         | 1.1.6              | wings-1.1.6-1.12.2.jar                             | None                                     |
	| LC    | mowzies_wings                 | 1.0.0              | wings-1.1.6-1.12.2.jar                             | None                                     |
	| LC    | bauble_wings                  | 1.0.0              | wings-1.1.6-1.12.2.jar                             | None                                     |
	| LC    | zombieawareness               | 1.12.1-1.11.16     | zombieawareness-1.12.1-1.11.16.jar                 | None                                     |
	| LC    | jurassicraft                  | 2.1.23             | JurassiCraft-1.12.2-2.1.23.jar                     | None                                     |
	| LC    | mysticallib                   | 1.12.2-1.7.0       | mysticallib-1.12.2-1.7.0.jar                       | None                                     |
	| UD    | mclib_core                    | 2.0.1              | minecraft.jar                                      | None                                     |
	| UD    | mobends_wings                 | 1.0.0              | wings-1.1.6-1.12.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
McLib core mod (mclib-2.0.1-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
HCASM (HammerLib-1.12.2-2.0.6.19.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
pymtech (PymTech-1.12.2-1.0.2.jar)
  lucraft.mods.pymtech.core.PymTechClassTransformer
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.20.jar)
  
FMLModule (mdxlib-3.0.0.26.jar)
  com.asx.mdx.AccessTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8729' Renderer: 'Intel(R) UHD Graphics 630'
	HammerCore Debug Information: 
Dependent Mods:
    -Improvable Skills (improvableskills) @65r

	Patchouli open book context: n/a
	
	
	If anyone knows how to fix this please tell me, I've been trying to fix it for hours.

**Comment by FoxMcloud5655** [comment]
Go update your mods.  Your version of Draconic Evolution (at the very least) is out-of-date.  I highly recommend updating the rest of your mods too.

**Comment by Espernos** [comment]
> Go update your mods. Your version of Draconic Evolution (at the very least) is out-of-date. I highly recommend updating the rest of your mods too.

the thing is i downloaded them using a modpack on forge so it will be hard to do so

**Comment by FoxMcloud5655** [comment]
CurseForge allows you to update your mods super easily; don't know what you're on about :P

If it's a modpack you are launching from CurseForge (which it appears as though you are from what I can tell), you can click on the modpack in question, click on the three dots in the upper left corner of the center of the screen, then select "Profile Options".  You can then select "Allow content management for this profile" to update your mods.  You can also add mods in this way (rather than downloading and adding them manually like you did) to ensure dependencies are downloaded as well.  Versions of mods aren't checked, unfortunately, but 1.12.2 is old enough that updating all of your mods has a very high chance of not breaking anything and only fixing issues.

**Comment by Espernos** [comment]
nvm i redownloaded the modpack and now it works
